### ISSUE TITLE
gameEditor binary fails to load correctly

### ISSUE THREAD

**Issue by ghost** [game-editor/game-editor#10]
1. Compile the 'master' branch on Windows 8.1 with Visual Studio Community 2015.
2. The resulting binary for gameEditor.exe in the output directory fails to load.  There is a window with title but no welcome screen.  The window fails to close and the user must ctrl+alt+del and end the task.
3. Copying the binary to the 'bin' folder where the older binary is located also fails to load correctly.

By 'failing to load' I mean there is a black screen.  No grid or even menu, a black screen of death.  The program does not segfault or close unexpectedly however and the user can fullscreen or window the program and move the window around.

**Comment by skydereign** [comment]
I merged in the update changes from the linux branch. It should work now. Let me know if it doesn't (testing on windows 10).

Currently visual studio tries to run the wrong executable. The correct executable is output/gameEditor.exe. The executables in the bin directory are meant to be the engine binary files which allow you to export, so they are not meant to be run like the editor.

**Comment by ghost** [comment]
The merge seems to work, compiles and runs just fine.

Thanks!
